### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by oxomoto** [javierarce/tumblr-photo-export#8]
After following all the steps I get this Unauthorized issue.

<img width="517" alt="screen shot 2016-06-27 at 12 26 43" src="https://cloud.githubusercontent.com/assets/20146315/16376975/a9b7a31e-3c63-11e6-82b6-ae719ddb8bb4.png">

**Comment by javierarce** [comment]
Hi, @oxomoto. Have you checked that the `api_key` and `username` are correctly set [here](https://github.com/javierarce/tumblr-photo-export/blob/master/export.rb#L5)?

**Comment by QuantumOtter** [comment]
Was a fix ever found for this issue? I'm getting the same error

**Comment by javierarce** [comment]
@QuantumOtter did you read my previous comment?

**Comment by QuantumOtter** [comment]
Going over it again, I was able to fix it. Thanks!

**Comment by javierarce** [comment]
@QuantumOtter: cool! 😄
